### ISSUE TITLE
Add Large Chipyard Configs

### ISSUE THREAD

**Issue by seldridge** [circt/perf#2]
Some of the largest open source FIRRTL files will come from [`ucb-bar/chipyard`](https://github.com/ucb-bar/chipyard/). Investigate building a configuration here that would be "real", but also adequately stress CIRCT.

Some things to investigate:

- [ ] MegaBoomConfig
- [ ] GigaBoomConfig
- [ ] Mixed cores (different Rocket cores mixed with differently sized BOOM cores)
- [ ] Heterogeneous use of accelerators (Hwacha, Gemmini, etc.)

**Comment by seldridge** [comment]
For this to work on mid form with these configurations, a solution to https://github.com/llvm/circt/issues/1181 is needed. Optimized low form works for these (after rearranging modules to be def-before-use), but I don't know if running on optimized low form is actually a useful performance test.

**Comment by lattner** [comment]
+1 +1 +1, I'd love to see several of these in the tester.

**Comment by lattner** [comment]
Awesome, looks great thank you!
