### ISSUE TITLE
Memory graph shows single bytes

### ISSUE THREAD

**Issue by fabianschuiki** [circt/perf#3]
The [graph](https://circt.org/perf/) for "test2, firtool, memory" shows 0.5B to 1.0B on the Y axis. I guess that's supposed to be "billions". Can we switch these to "G" SI prefix as in GB?

**Comment by drom** [comment]
should be better now
https://github.com/circt/perf/commit/cc3ba9081ea5657fa58c7e702ee7babbfd6dfe5e

**Comment by fabianschuiki** [comment]
Looks great :eyes: :raised_hands:
